name: Gerar APK jdp_system-26

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Java Automático
      uses: actions/setup-java@v4
      with:
        java-version: '11' # Versão mais comum para compatibilidade com Gradle 8.x
        distribution: 'temurin'

    - name: Dar permissão ao Gradle
      run: chmod +x gradlew

    - name: Compilar APK
      run: ./gradlew assembleDebug

    - name: Disponibilizar o APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: jdp_sustem-26 Pronta
        path: app/build/outputs/apk/debug/app-debug.apk

